### ISSUE TITLE
support non-css assets

### ISSUE THREAD

**Issue by matthewmueller** [makojs/css#4]
https://github.com/makojs/css/blob/160a5b8d8c11f35ecf974b9c0f15d554ac46b63c/index.js#L36

same as: https://github.com/makojs/js/pull/9

could probably be simplified to just checking for `css` since things should be resolved by the `predependencies` hook.

**Comment by dominicbarnes** [comment]
+1

I will gladly accept a PR, or I will do this myself later tonight. :)

**Comment by dominicbarnes** [comment]
Fixed in 0.5.2
