### ISSUE TITLE
Project root relative imports

### ISSUE THREAD

**Issue by darsain** [makojs/css#54]
To protect against drowning in the see of relative paths such as `@import '../../module/foo'`, and make maintenance easier.

In this project structure:

```
module/
  foo.css
index.css
package.json
```

With this `package.json`:

```js
{
  "name": "app",
  ...
}
```

Doing:

```css
@import 'app/module/foo';
```

in any project file should correctly import `module/foo.css`.

The `package.json` should be looked up in mako's `root`.

This extends the node's resolve logic with nonstandard behavior, and should therefore be used only in top level modules, which are not intended to be depended upon. We should also boldly warn against using it anywhere else.

**Comment by dominicbarnes** [comment]
This is being closed for the same reasons as makojs/js#72. In short, you can use `resolveOptions.paths` to set the project root as a path in addition to `node_modules` that will be searched for `require` paths.
